---
all:
  children:
    raspberry_pi:
      hosts:
        pi-media-server:
          ansible_host: 192.168.10.100  # IP do Raspberry Pi
          ansible_user: pi
          ansible_port: 2072  # Porta SSH customizada
          ansible_python_interpreter: /usr/bin/python3
          
          # Informações adicionais do host
          host_description: "Raspberry Pi Media Server"
          
      vars:
        # Variáveis comuns para todos os Raspberry Pi
        ansible_connection: ssh
        gather_facts: yes
